import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono, Tajawal, Space_Grotesk } from "next/font/google";
import { LanguageProvider } from "@/lib/LanguageContext";
import { ThemeProvider } from "@/lib/ThemeContext";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { Effects } from "./effects";
import "./globals.css";

// Tiny inline script that runs BEFORE React hydrates, so the user's
// preferred theme is already applied to <html> on first paint. Without
// this you'd see a flash of light theme before dark mode is applied.
// Falls back to the OS-level dark mode preference if no choice saved.
const themeBootScript = `
  try {
    var saved = localStorage.getItem('theme');
    var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    var theme = (saved === 'dark' || saved === 'light') ? saved : (prefersDark ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
  } catch (e) {
    document.documentElement.setAttribute('data-theme', 'light');
  }
`;

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});
const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-plex-mono",
  display: "swap",
});
const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
  display: "swap",
});
// Used for capability-card titles — gives them a modern, slightly tech vibe
// distinct from Inter (which is the brand body font everywhere else).
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

// Production URL — change once your real domain is connected (or set the env
// variable NEXT_PUBLIC_SITE_URL in your hosting provider).
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://shenatech.com";

const TITLE = "ShenaTech — Supply Chain Intelligence for the GCC";
const DESCRIPTION =
  "ShenaTech turns fragmented logistics signals into real-time decisions for freight operators across the GCC. Real-time visibility, predictive ETAs, freight marketplace, digital documentation.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  // Social preview (LinkedIn, WhatsApp, X, Slack, etc.). The image is
  // auto-generated by app/opengraph-image.tsx — no asset file needed.
  openGraph: {
    type: "website",
    siteName: "Shenatech",
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  // Favicon shown in the browser tab — uses the Shenatech logo at
  // frontend/public/logo.png. To change it, just replace that file.
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${inter.variable} ${plexMono.variable} ${tajawal.variable} ${spaceGrotesk.variable}`}
    >
      <head>
        {/* Theme boot script — runs synchronously before hydration to avoid
            a flash of the wrong theme on first load. */}
        <script dangerouslySetInnerHTML={{ __html: themeBootScript }} />
      </head>
      <body>
        <ThemeProvider>
          <LanguageProvider>
            <div className="scroll-progress" aria-hidden="true" />
            <Nav />
            {children}
            <Footer />
            <Effects />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
