import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono, Tajawal } from "next/font/google";
import { LanguageProvider } from "@/lib/LanguageContext";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { Effects } from "./effects";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});
const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-plex-mono",
  display: "swap",
});
const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
  display: "swap",
});

// Production URL — change once your real domain is connected (or set the env
// variable NEXT_PUBLIC_SITE_URL in your hosting provider).
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://shenatech.com";

const TITLE = "ShenaTech — Supply Chain Intelligence for the GCC";
const DESCRIPTION =
  "ShenaTech turns fragmented logistics signals into real-time decisions for freight operators across the GCC. Real-time visibility, predictive ETAs, freight marketplace, digital documentation.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  // Social preview (LinkedIn, WhatsApp, X, Slack, etc.). The image is
  // auto-generated by app/opengraph-image.tsx — no asset file needed.
  openGraph: {
    type: "website",
    siteName: "Shenatech",
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  // Favicon: gold "S" on a dark rounded-square background (app-icon style).
  icons: {
    icon: [
      {
        url:
          "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgcng9IjIyIiBmaWxsPSIjMEIwRDBGIi8+PHRleHQgeD0iNTAiIHk9Ijc0IiBmb250LWZhbWlseT0iSW50ZXIsQXJpYWwsc2Fucy1zZXJpZiIgZm9udC1zaXplPSI3MiIgZm9udC13ZWlnaHQ9IjkwMCIgZmlsbD0iI0ZDQkEwMiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+UzwvdGV4dD48L3N2Zz4=",
        type: "image/svg+xml",
      },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${inter.variable} ${plexMono.variable} ${tajawal.variable}`}
    >
      <body>
        <LanguageProvider>
          <div className="scroll-progress" aria-hidden="true" />
          <Nav />
          {children}
          <Footer />
          <Effects />
        </LanguageProvider>
      </body>
    </html>
  );
}
